title: Bahram Khanlarov
author:
  name: Bahram Khanlarov
  contact: Phone
        +41 79 253 56 99
        Linkedin
        https://www.linkedin.com/in/bahram-khan- 511982159/
        Email
        bahram.khanlarov@stud.hslu.ch
        Address
        Avenue des Alpes 102, 1820 Montreux, Switzerland 
logo: /assets/WhatsApp Image 2024-01-16 at 18.31.35.jpeg
description: Junior Data Analyst
show_downloads: true
theme: jekyll-theme-minimal



